[package]
name = "wooting-macros"
version = "0.2.0"
description = "Macro software made by Wooting."
authors = ["David Manca, Khang"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }




[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tauri = { version = "1.2", features = ["api-all", "icon-png", "system-tray"] }
rdev = { version = "0.5", features = ["unstable_grab", "serde", "serialize"] }
halfbrown = { version = "0.1", features = ["serde"] }
idasen-cli = "0.1"
lazy_static = "1.4"
tokio = { version = "1.21", features = ["full"] }
tokio-serde = { version = "0.8", features = ["json"] }
opener = "0.5"
#windows = { version = "0.43", features = ["Win32_Media_Audio", "Win32_Foundation", "Win32_System", "Win32_System_Com"] }
winaudio = "1.0.2"
rodio = "0.16.0"
brightness = { version = "0.5", optional = true }
futures = "0.3.25"
copypasta = { version = "0.8.1", features = ["smithay-clipboard"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]


